export const TEMPLATES = [
  {
    name: 'System Classic',
    preview: 'bg-gradient-to-br from-[#FAF6F2] to-[#DEC8C4]',
    backgroundColor: 'bg-[#FAF6F2]',
    cardBackground: 'bg-white',
    textColor: 'text-[#5C3530]',
    titleColor: 'text-[#3D1A16]',
    accentColor: 'bg-[#C9A09A]',
    accentText: 'text-[#C9A09A]',
    borderColor: 'border-[#DEC8C4]',
    dividerColor: 'bg-[#DEC8C4]',
    buttonClass: 'bg-[#5C3530] text-[#FAF6F2] hover:bg-[#3D1A16]',
    accent: 'Dusty Rose (Default)',
    ribbonColor: '#C9A09A',
  },
  {
    name: 'Elegant Rose',
    preview: 'bg-gradient-to-br from-[#FDF0F3] to-[#E8B0BE]',
    backgroundColor: 'bg-[#FAFAFA]',
    cardBackground: 'bg-[#FDF0F3]',
    textColor: 'text-[#6B1F35]',
    titleColor: 'text-[#4A0A20]',
    accentColor: 'bg-[#C4607A]',
    accentText: 'text-[#C4607A]',
    borderColor: 'border-[#E8B0BE]',
    dividerColor: 'bg-[#E8B0BE]',
    buttonClass: 'bg-[#6B1F35] text-[#FDF0F3] hover:bg-[#4A0A20]',
    accent: 'Dusty Pink',
    ribbonColor: '#C4607A',
  },
  {
    name: 'Golden Classic',
    preview: 'bg-gradient-to-br from-[#FDF5DC] to-[#E8D080]',
    backgroundColor: 'bg-[#F8F7F2]',
    cardBackground: 'bg-[#FDF5DC]',
    textColor: 'text-[#4A3010]',
    titleColor: 'text-[#3D2B0A]',
    accentColor: 'bg-[#C9A84C]',
    accentText: 'text-[#B8922A]',
    borderColor: 'border-[#E8D080]',
    dividerColor: 'bg-[#E8D080]',
    buttonClass: 'bg-[#3D2B0A] text-[#FDF5DC] hover:bg-[#2A1A00]',
    accent: 'Warm Gold',
    ribbonColor: '#B8922A',
  },
  {
    name: 'Sage Garden',
    preview: 'bg-gradient-to-br from-[#E8EFE6] to-[#A8C8A6]',
    backgroundColor: 'bg-[#F2F5F1]',
    cardBackground: 'bg-[#E8EFE6]',
    textColor: 'text-[#2A4028]',
    titleColor: 'text-[#243C22]',
    accentColor: 'bg-[#6A9668]',
    accentText: 'text-[#5E8A5C]',
    borderColor: 'border-[#A8C8A6]',
    dividerColor: 'bg-[#A8C8A6]',
    buttonClass: 'bg-[#243C22] text-[#E8EFE6] hover:bg-[#162814]',
    accent: 'Sage Green',
    ribbonColor: '#5E8A5C',
  },
  {
    name: 'Midnight Serenade',
    preview: 'bg-gradient-to-br from-[#1C2233] to-[#2E3A52]',
    backgroundColor: 'bg-[#0F121A]',
    cardBackground: 'bg-[#1C2233]',
    textColor: 'text-[#CBD5E8]',
    titleColor: 'text-[#E8EDF7]',
    accentColor: 'bg-[#7B8FC2]',
    accentText: 'text-[#7B8FC2]',
    borderColor: 'border-[#2E3A52]',
    dividerColor: 'bg-[#3A4A66]',
    buttonClass: 'bg-[#E8EDF7] text-[#1C2233] hover:bg-white',
    accent: 'Periwinkle',
    ribbonColor: '#7B8FC2',
  },
  {
    name: 'Emerald Forest',
    preview: 'bg-gradient-to-br from-[#0B3D2E] to-[#0F5C40]',
    backgroundColor: 'bg-[#051A14]',
    cardBackground: 'bg-[#0B3D2E]',
    textColor: 'text-[#A8DCC4]',
    titleColor: 'text-[#DFFAED]',
    accentColor: 'bg-[#3DB882]',
    accentText: 'text-[#3DB882]',
    borderColor: 'border-[#0F5C40]',
    dividerColor: 'bg-[#1A7050]',
    buttonClass: 'bg-[#DFFAED] text-[#0B3D2E] hover:bg-white',
    accent: 'Jewel Emerald',
    ribbonColor: '#3DB882',
  },
  {
    name: 'Terracotta Sun',
    preview: 'bg-gradient-to-br from-[#7A2C12] to-[#C04E20]',
    backgroundColor: 'bg-[#FAF3F0]',
    cardBackground: 'bg-[#7A2C12]',
    textColor: 'text-[#FFD9B3]',
    titleColor: 'text-[#FFE8D0]',
    accentColor: 'bg-[#E8834A]',
    accentText: 'text-[#E8834A]',
    borderColor: 'border-[#C04E20]',
    dividerColor: 'bg-[#C04E20]',
    buttonClass: 'bg-[#FFE8D0] text-[#5A1A06] hover:bg-white',
    accent: 'Burnt Orange',
    ribbonColor: '#E8834A',
  },
  {
    name: 'Noir Romantique',
    preview: 'bg-gradient-to-br from-[#1A1018] to-[#4A2038]',
    backgroundColor: 'bg-[#120A10]',
    cardBackground: 'bg-[#1A1018]',
    textColor: 'text-[#E0C0D0]',
    titleColor: 'text-[#F5E0EA]',
    accentColor: 'bg-[#C4789A]',
    accentText: 'text-[#C4789A]',
    borderColor: 'border-[#4A2038]',
    dividerColor: 'bg-[#4A2038]',
    buttonClass: 'bg-[#F5E0EA] text-[#2A1020] hover:bg-white',
    accent: 'Burgundy Rose',
    ribbonColor: '#C4789A',
  },
  {
    name: 'Bohemian Earth',
    preview: 'bg-gradient-to-br from-[#D4A373] to-[#A98467]',
    backgroundColor: 'bg-[#Fefae0]',
    cardBackground: 'bg-[#D4A373]',
    textColor: 'text-[#FAEDCD]',
    titleColor: 'text-[#FAEDCD]',
    accentColor: 'bg-[#BC6C25]',
    accentText: 'text-[#BC6C25]',
    borderColor: 'border-[#A98467]',
    dividerColor: 'bg-[#A98467]',
    buttonClass: 'bg-[#606C38] text-[#FEFAE0] hover:bg-[#283618]',
    accent: 'Terracotta & Olive',
    ribbonColor: '#BC6C25',
  },
  {
    name: 'Midnight Royal',
    preview: 'bg-gradient-to-br from-[#023047] to-[#219EBC]',
    backgroundColor: 'bg-[#F1F5F9]',
    cardBackground: 'bg-[#023047]',
    textColor: 'text-[#8ECAE6]',
    titleColor: 'text-[#FFB703]',
    accentColor: 'bg-[#FFB703]',
    accentText: 'text-[#FFB703]',
    borderColor: 'border-[#219EBC]',
    dividerColor: 'bg-[#219EBC]',
    buttonClass: 'bg-[#FB8500] text-white hover:bg-[#E67E00]',
    accent: 'Navy & Gold',
    ribbonColor: '#FFB703',
  },
  {
    name: 'Minimalist Slate',
    preview: 'bg-gradient-to-br from-[#2D3436] to-[#636E72]',
    backgroundColor: 'bg-white',
    cardBackground: 'bg-[#2D3436]',
    textColor: 'text-[#DFE6E9]',
    titleColor: 'text-white',
    accentColor: 'bg-[#ADADB2]',
    accentText: 'text-[#ADADB2]',
    borderColor: 'border-[#636E72]',
    dividerColor: 'bg-[#636E72]',
    buttonClass:
      'bg-white text-[#2D3436] border border-[#2D3436] hover:bg-[#DFE6E9]',
    accent: 'Modern Monochrome',
    ribbonColor: '#ADADB2',
  },
  {
    name: 'Forest Mist',
    preview: 'bg-gradient-to-br from-[#2D6A4F] to-[#52B788]',
    backgroundColor: 'bg-[#F0F4F2]',
    cardBackground: 'bg-[#1B4332]',
    textColor: 'text-[#D8F3DC]',
    titleColor: 'text-[#95D5B2]',
    accentColor: 'bg-[#52B788]',
    accentText: 'text-[#52B788]',
    borderColor: 'border-[#2D6A4F]',
    dividerColor: 'bg-[#2D6A4F]',
    buttonClass: 'bg-[#D8F3DC] text-[#1B4332] hover:bg-white',
    accent: 'Deep Emerald',
    ribbonColor: '#52B788',
  },
  {
    name: 'Peach Sorbet',
    preview: 'bg-gradient-to-br from-[#FFECD2] to-[#FCB69F]',
    backgroundColor: 'bg-[#FFF9F5]',
    cardBackground: 'bg-[#FCB69F]',
    textColor: 'text-[#4A2C2A]',
    titleColor: 'text-[#842D25]',
    accentColor: 'bg-[#FF9A8B]',
    accentText: 'text-[#FF9A8B]',
    borderColor: 'border-[#F9D1D1]',
    dividerColor: 'bg-[#F9D1D1]',
    buttonClass: 'bg-[#842D25] text-white hover:bg-[#4A0000]',
    accent: 'Warm Coral',
    ribbonColor: '#FF9A8B',
  },
  {
    name: 'Crimson Velvet',
    preview: 'bg-gradient-to-br from-[#4A0E0E] to-[#8B0000]',
    backgroundColor: 'bg-[#F9F6F6]',
    cardBackground: 'bg-[#4A0E0E]',
    textColor: 'text-[#E5D5D5]',
    titleColor: 'text-[#D4AF37]',
    accentColor: 'bg-[#D4AF37]',
    accentText: 'text-[#D4AF37]',
    borderColor: 'border-[#8B0000]',
    dividerColor: 'bg-[#8B0000]',
    buttonClass: 'bg-[#D4AF37] text-[#4A0E0E] hover:bg-[#C19A28]',
    accent: 'Maroon Gold',
    ribbonColor: '#D4AF37',
  },
  {
    name: 'Vintage Matcha',
    preview: 'bg-gradient-to-br from-[#ADC178] to-[#6C584C]',
    backgroundColor: 'bg-[#F0EAD6]',
    cardBackground: 'bg-[#ADC178]',
    textColor: 'text-[#6C584C]',
    titleColor: 'text-[#352F44]',
    accentColor: 'bg-[#A98467]',
    accentText: 'text-[#A98467]',
    borderColor: 'border-[#DDE5B6]',
    dividerColor: 'bg-[#DDE5B6]',
    buttonClass: 'bg-[#6C584C] text-[#F0EAD6] hover:bg-[#352F44]',
    accent: 'Olive & Earth',
    ribbonColor: '#A98467',
  },
];
