export const PACKAGES = [
  {
    name: 'Kenangan',
    price: '299K',
    description: 'Cocok untuk pernikahan intim',
    features: [
      '1 Halaman Undangan',
      'Link Personal per Tamu',
      'RSVP Digital',
      'Buku Tamu Digital',
      'Countdown Timer',
      'Galeri Foto (max 6)',
      'Musik Latar',
      'Masa Aktif 3 Bulan',
    ],
    popular: false,
    cta: 'Pilih Paket',
  },
  {
    name: 'Bahagia',
    price: '499K',
    description: 'Pilihan terpopuler untuk pernikahan modern',
    features: [
      'Semua Fitur Kenangan',
      'Galeri Foto (max 15)',
      'Maps Integration',
      'QR Code Undangan',
      'Export Data Tamu (CSV)',
      'Masa Aktif 6 Bulan',
      'Support Prioritas',
    ],
    popular: true,
    cta: 'Pilih Paket',
  },
  {
    name: 'Selamanya',
    price: '799K',
    description: 'Paket lengkap tanpa batas',
    features: [
      'Semua Fitur Bahagia',
      'Galeri Foto Unlimited',
      'Video Pre-wedding',
      'Analytics Dashboard',
      'Custom Pesan Pembuka',
      'Password Protection',
      'Masa Aktif Selamanya',
      'Support Premium 24/7',
    ],
    popular: false,
    cta: 'Pilih Paket',
  },
];
