export type Template = {
  name: string;
  accent: string;
  ribbonColor: string;
  bookPreview: string;
  cssVars: {
    '--background': string;
    '--card': string;
    '--card-foreground': string;
    '--foreground': string;
    '--muted-foreground': string;
    '--primary': string;
    '--primary-foreground': string;
    '--primary-dark': string;
    '--primary-subtle': string;
    '--border': string;
    '--accent': string;
    '--accent-foreground': string;
    '--muted': string;
  };
};

export const TEMPLATES: Template[] = [
  {
    name: 'System Classic',
    accent: 'Dusty Rose (Default)',
    ribbonColor: '#C9A09A',
    bookPreview: 'bg-gradient-to-br from-[#FAF6F2] to-[#DEC8C4]',
    cssVars: {
      '--background': '#faf7f4',
      '--card': '#f3ede6',
      '--card-foreground': '#2e2e2e',
      '--foreground': '#2e2e2e',
      '--muted-foreground': '#7a7069',
      '--primary': '#c9a0a0',
      '--primary-foreground': '#ffffff',
      '--primary-dark': '#8b5e6a',
      '--primary-subtle': '#e9deda',
      '--border': '#e8d5cc',
      '--accent': '#c9a84c',
      '--accent-foreground': '#ffffff',
      '--muted': '#f3ede6',
    },
  },
  {
    name: 'Elegant Rose',
    accent: 'Dusty Pink',
    ribbonColor: '#C4607A',
    bookPreview: 'bg-gradient-to-br from-[#FDF0F3] to-[#E8B0BE]',
    cssVars: {
      '--background': '#FAFAFA',
      '--card': '#FDF0F3',
      '--card-foreground': '#6B1F35',
      '--foreground': '#4A0A20',
      '--muted-foreground': '#9A5060',
      '--primary': '#C4607A',
      '--primary-foreground': '#FFFFFF',
      '--primary-dark': '#6B1F35',
      '--primary-subtle': '#FAEAED',
      '--border': '#E8B0BE',
      '--accent': '#FAEAED',
      '--accent-foreground': '#6B1F35',
      '--muted': '#FAEAED',
    },
  },
  {
    name: 'Golden Classic',
    accent: 'Warm Gold',
    ribbonColor: '#B8922A',
    bookPreview: 'bg-gradient-to-br from-[#FDF5DC] to-[#E8D080]',
    cssVars: {
      '--background': '#F8F7F2',
      '--card': '#FDF5DC',
      '--card-foreground': '#4A3010',
      '--foreground': '#3D2B0A',
      '--muted-foreground': '#8A7040',
      '--primary': '#C9A84C',
      '--primary-foreground': '#FDF5DC',
      '--primary-dark': '#3D2B0A',
      '--primary-subtle': '#FAF0C0',
      '--border': '#E8D080',
      '--accent': '#FAF0C0',
      '--accent-foreground': '#4A3010',
      '--muted': '#FAF0C0',
    },
  },
  {
    name: 'Sage Garden',
    accent: 'Sage Green',
    ribbonColor: '#5E8A5C',
    bookPreview: 'bg-gradient-to-br from-[#E8EFE6] to-[#A8C8A6]',
    cssVars: {
      '--background': '#F2F5F1',
      '--card': '#E8EFE6',
      '--card-foreground': '#2A4028',
      '--foreground': '#243C22',
      '--muted-foreground': '#5A7A58',
      '--primary': '#6A9668',
      '--primary-foreground': '#E8EFE6',
      '--primary-dark': '#243C22',
      '--primary-subtle': '#D8EAD6',
      '--border': '#A8C8A6',
      '--accent': '#D8EAD6',
      '--accent-foreground': '#2A4028',
      '--muted': '#D8EAD6',
    },
  },
  {
    name: 'Midnight Serenade',
    accent: 'Periwinkle',
    ribbonColor: '#7B8FC2',
    bookPreview: 'bg-gradient-to-br from-[#1C2233] to-[#2E3A52]',
    cssVars: {
      '--background': '#0F121A',
      '--card': '#1C2233',
      '--card-foreground': '#CBD5E8',
      '--foreground': '#E8EDF7',
      '--muted-foreground': '#8892B0',
      '--primary': '#7B8FC2',
      '--primary-foreground': '#0F121A',
      '--primary-dark': '#E8EDF7',
      '--primary-subtle': '#252D42',
      '--border': '#2E3A52',
      '--accent': '#252D42',
      '--accent-foreground': '#CBD5E8',
      '--muted': '#252D42',
    },
  },
  {
    name: 'Emerald Forest',
    accent: 'Jewel Emerald',
    ribbonColor: '#3DB882',
    bookPreview: 'bg-gradient-to-br from-[#0B3D2E] to-[#0F5C40]',
    cssVars: {
      '--background': '#051A14',
      '--card': '#0B3D2E',
      '--card-foreground': '#A8DCC4',
      '--foreground': '#DFFAED',
      '--muted-foreground': '#7ABEA0',
      '--primary': '#3DB882',
      '--primary-foreground': '#051A14',
      '--primary-dark': '#DFFAED',
      '--primary-subtle': '#0D4A36',
      '--border': '#0F5C40',
      '--accent': '#0D4A36',
      '--accent-foreground': '#A8DCC4',
      '--muted': '#0D4A36',
    },
  },
  {
    name: 'Terracotta Sun',
    accent: 'Burnt Orange',
    ribbonColor: '#E07840',
    bookPreview: 'bg-gradient-to-br from-[#7A2C12] to-[#C04E20]',
    cssVars: {
      '--background': '#2A0E06',
      '--card': '#3D1608',
      '--card-foreground': '#FFD4A8',
      '--foreground': '#FFE8D0',
      '--muted-foreground': '#E0B090',
      '--primary': '#E07840',
      '--primary-foreground': '#2A0E06',
      '--primary-dark': '#FFE8D0',
      '--primary-subtle': '#501808',
      '--border': '#C05A28',
      '--accent': '#501808',
      '--accent-foreground': '#FFD4A8',
      '--muted': '#501808',
    },
  },
  {
    name: 'Noir Romantique',
    accent: 'Burgundy Rose',
    ribbonColor: '#C4789A',
    bookPreview: 'bg-gradient-to-br from-[#1A1018] to-[#4A2038]',
    cssVars: {
      '--background': '#120A10',
      '--card': '#1A1018',
      '--card-foreground': '#E0C0D0',
      '--foreground': '#F5E0EA',
      '--muted-foreground': '#C0A0B0',
      '--primary': '#C4789A',
      '--primary-foreground': '#120A10',
      '--primary-dark': '#F5E0EA',
      '--primary-subtle': '#281020',
      '--border': '#4A2038',
      '--accent': '#281020',
      '--accent-foreground': '#E0C0D0',
      '--muted': '#281020',
    },
  },
  {
    name: 'Bohemian Earth',
    accent: 'Terracotta & Olive',
    ribbonColor: '#BC6C25',
    bookPreview: 'bg-gradient-to-br from-[#D4A373] to-[#A98467]',
    cssVars: {
      '--background': '#FEFAE0',
      '--card': '#D4A373',
      '--card-foreground': '#FAEDCD',
      '--foreground': '#283618',
      '--muted-foreground': '#5C4030',
      '--primary': '#BC6C25',
      '--primary-foreground': '#FEFAE0',
      '--primary-dark': '#283618',
      '--primary-subtle': '#E8C898',
      '--border': '#A98467',
      '--accent': '#E8D8B0',
      '--accent-foreground': '#283618',
      '--muted': '#E8D8B0',
    },
  },
  {
    name: 'Midnight Royal',
    accent: 'Navy & Gold',
    ribbonColor: '#FFB703',
    bookPreview: 'bg-gradient-to-br from-[#023047] to-[#219EBC]',
    cssVars: {
      '--background': '#F1F5F9',
      '--card': '#023047',
      '--card-foreground': '#8ECAE6',
      '--foreground': '#8ECAE6',
      '--muted-foreground': '#5BA4BE',
      '--primary': '#FFB703',
      '--primary-foreground': '#023047',
      '--primary-dark': '#8ECAE6',
      '--primary-subtle': '#034060',
      '--border': '#219EBC',
      '--accent': '#034060',
      '--accent-foreground': '#8ECAE6',
      '--muted': '#034060',
    },
  },
  {
    name: 'Minimalist Slate',
    accent: 'Modern Monochrome',
    ribbonColor: '#2D3748',
    bookPreview: 'bg-gradient-to-br from-[#EDF2F7] to-[#DFE6E9]',
    cssVars: {
      '--background': '#F7FAFC',
      '--card': '#FFFFFF',
      '--card-foreground': '#2D3748',
      '--foreground': '#2D3748',
      '--muted-foreground': '#718096',
      '--primary': '#4A5568',
      '--primary-foreground': '#FFFFFF',
      '--primary-dark': '#1A202C',
      '--primary-subtle': '#EDF2F7',
      '--border': '#4A5568',
      '--accent': '#4A5568',
      '--accent-foreground': '#FFFFFF',
      '--muted': '#EDF2F7',
    },
  },
  {
    name: 'Forest Mist',
    accent: 'Deep Emerald',
    ribbonColor: '#064E3B',
    bookPreview: 'bg-gradient-to-br from-[#DCE8E2] to-[#B6D1C4]',
    cssVars: {
      '--background': '#E8F0ED',
      '--card': '#FFFFFF',
      '--card-foreground': '#064E3B',
      '--foreground': '#064E3B',
      '--muted-foreground': '#5E7A6C',
      '--primary': '#064E3B',
      '--primary-foreground': '#FFFFFF',
      '--primary-dark': '#064E3B',
      '--primary-subtle': '#DCE8E2',
      '--border': '#064E3B',
      '--accent': '#064E3B',
      '--accent-foreground': '#FFFFFF',
      '--muted': '#DCE8E2',
    },
  },
  {
    name: 'Peach Sorbet',
    accent: 'Warm Coral',
    ribbonColor: '#FF9A8B',
    bookPreview: 'bg-gradient-to-br from-[#FFECD2] to-[#FCB69F]',
    cssVars: {
      '--background': '#FFF9F5',
      '--card': '#FCB69F',
      '--card-foreground': '#4A2C2A',
      '--foreground': '#4A2C2A',
      '--muted-foreground': '#8A5050',
      '--primary': '#FF9A8B',
      '--primary-foreground': '#FFFFFF',
      '--primary-dark': '#842D25',
      '--primary-subtle': '#FFE8DC',
      '--border': '#F9D1D1',
      '--accent': '#FFE8DC',
      '--accent-foreground': '#4A2C2A',
      '--muted': '#FFE8DC',
    },
  },
  {
    name: 'Crimson Velvet',
    accent: 'Maroon Gold',
    ribbonColor: '#D4AF37',
    bookPreview: 'bg-gradient-to-br from-[#FDEAEA] to-[#F3D5D5]',
    cssVars: {
      '--background': '#FDF8F8',
      '--card': '#FFFFFF',
      '--card-foreground': '#4A0E0E',
      '--foreground': '#4A0E0E',
      '--muted-foreground': '#8B5E5E',
      '--primary': '#D4AF37',
      '--primary-foreground': '#FFFFFF',
      '--primary-dark': '#4A0E0E',
      '--primary-subtle': '#FDEAEA',
      '--border': '#D4AF37',
      '--accent': '#6A1A1A',
      '--accent-foreground': '#FFFFFF',
      '--muted': '#FDEAEA',
    },
  },
  {
    name: 'Vintage Matcha',
    accent: 'Olive & Earth',
    ribbonColor: '#606C38',
    bookPreview: 'bg-gradient-to-br from-[#DDE5B6] to-[#ADC178]',
    cssVars: {
      '--background': '#F0EAD6',
      '--card': '#ADC178',
      '--card-foreground': '#352F44',
      '--foreground': '#352F44',
      '--muted-foreground': '#6C584C',
      '--primary': '#A98467',
      '--primary-foreground': '#F0EAD6',
      '--primary-dark': '#352F44',
      '--primary-subtle': '#D8E4A8',
      '--border': '#DDE5B6',
      '--accent': '#D8E4A8',
      '--accent-foreground': '#352F44',
      '--muted': '#D8E4A8',
    },
  },
];
